# Generated by Django 5.1.5 on 2025-02-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chat_message_userprofile_delete_chatmessage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="images",
            field=models.ImageField(blank=True, null=True, upload_to="aichat_images/"),
        ),
    ]
